theme = "modus_vivendi_deuteranopia"

[editor]

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["select_mode", "extend_to_line_bounds"]
L = ["repeat_last_motion"]
