theme = "modus_vivendi_deuteranopia"

[editor]
mouse = false
clipboard-provider = "pasteboard"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
wrap-indicator = ""

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
V = ["select_mode", "extend_to_line_bounds", "extend_to_line_end"]
G = "goto_file_end"

p = ["paste_clipboard_after", "collapse_selection"]

y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]

D = ["extend_to_line_end", "delete_selection", "normal_mode"]


"space" = { t = ":sh tmux display-popup -E \"yazi\"" }

[keys.select]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
p = ["paste_clipboard_after", "collapse_selection"]

G = "goto_file_end"
