[[language]]
name = "python"
language-servers = [ "pyright", "ruff-lsp" ]
[language-server.ruff-lsp]
command = "ruff-lsp"

[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
