#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected="$1"
else
   selected=$(find "$HOME/me/notes/" -maxdepth 2 -type f -name '*.md' | fzf)
fi

if [[ -z "$selected" ]]; then
    exit 0
fi
nvim -c "set wrap" "$selected"

