[tintim]
lambdas:~/workspace/work/tintim-lambdas
locals:~/workspace/work/tintim-locals
alcazar:~/workspace/work/tintim-alcazar
waha:~/workspace/work/tintim-waha

[sre]
shell:~/workspace
infrastructure:~/workspace/work/tintim-infrastructure
fleet:~/workspace/work/tintim-k3s-fleet
gateway:~/workspace/work/tintim-k3s-gateway
k9s:~/workspace/work|k9s
docs:~/workspace/work/tintim-docs


[personal]
claude:~/workspace|claude
dotfiles:~/workspace/dotfiles
notes:~/me/notes/

[logs]
personal-log:~/me/notes|nvim personal-log.md
work-log:~/me/notes|nvim work-log.md

[labs]
shell:~/workspace
lab:~/workspace/labs
server:~/workspace
blog:~/workspace/writing/blog
mental-models:~/workspace/writing/mental-models
unikraft:~/workspace/projects/unikraft
linux:~/workspace/projects/linux
