set -g status-style 'bg=#333333 fg=#5eacd3'
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# Set the prefix key
set -g prefix C-t

# Bind a key to split pane horizontally
bind-key b split-window -h -c "#{pane_current_path}" 
bind-key v split-window -v -c "#{pane_current_path}"

# Find projects
bind-key -r f run-shell "tmux neww ~/.config/tmux/work-sessionizer"

# Write
bind-key -r 0 run-shell "tmux split-window -v ~/.config/tmux/notes-sessionizer"
# bind-key -r 0 run-shell "tmux neww ~/.config/tmux/notes-sessionizer"


bind-key l select-pane -R
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
